//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTSoftware.Core.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMsg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NTSoftware.Core.Shared.ErrorMsg", typeof(ErrorMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã tồn tại..
        /// </summary>
        public static string ACCOUNT_EXISTED {
            get {
                return ResourceManager.GetString("ACCOUNT_EXISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của bạn đã hết hạn hoặc chưa được kích hoạt. Vui lòng thử lại sau.
        /// </summary>
        public static string ACCOUNT_EXPRIED_NEW {
            get {
                return ResourceManager.GetString("ACCOUNT_EXPRIED_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không tồn tại. Vui lòng thử lại sau..
        /// </summary>
        public static string ACCOUNT_NOT_EXITS {
            get {
                return ResourceManager.GetString("ACCOUNT_NOT_EXITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã đến giới hạn nhân viên của hợp đồng. Không thể thêm nhân viên.
        /// </summary>
        public static string CAN_NOT_ADD_EMPLOYEE {
            get {
                return ResourceManager.GetString("CAN_NOT_ADD_EMPLOYEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa hợp đồng đang chạy hoặc kết thúc.
        /// </summary>
        public static string CAN_NOT_DELELE_CONTRACT {
            get {
                return ResourceManager.GetString("CAN_NOT_DELELE_CONTRACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi mật khẩu không thành công.
        /// </summary>
        public static string CHANGE_PASSWORD_FAILED {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu thành công.
        /// </summary>
        public static string CHANGE_PASSWORD_SUCCESS {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa công ty đang còn hạn hợp đồng.
        /// </summary>
        public static string COMPANY_CAN_NOT_DELETE {
            get {
                return ResourceManager.GetString("COMPANY_CAN_NOT_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty bạn đã hết hợp đồng. Thêm hợp đồng mới để tiếp tục..
        /// </summary>
        public static string COMPANY_EXPRIED {
            get {
                return ResourceManager.GetString("COMPANY_EXPRIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa công ty đã có hợp đồng.
        /// </summary>
        public static string COMPANY_HAS_CONTRACT {
            get {
                return ResourceManager.GetString("COMPANY_HAS_CONTRACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty không tồn tại. Vui lòng thử lại sau..
        /// </summary>
        public static string COMPANY_NOT_EXITS {
            get {
                return ResourceManager.GetString("COMPANY_NOT_EXITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty chưa đến hạn hợp đồng. Vui lòng quay lại sau..
        /// </summary>
        public static string COMPANY_NOT_READY {
            get {
                return ResourceManager.GetString("COMPANY_NOT_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp đồng công ty chưa được kích hoạt. Thử lại sau..
        /// </summary>
        public static string CONTRACT_NEW {
            get {
                return ResourceManager.GetString("CONTRACT_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp đồng không tồn tại.
        /// </summary>
        public static string CONTRACT_NOT_EXIST {
            get {
                return ResourceManager.GetString("CONTRACT_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp đồng đã quá hạn. không thể kích hoạt.
        /// </summary>
        public static string CONTRACT_OUT_DATE {
            get {
                return ResourceManager.GetString("CONTRACT_OUT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu truyền lên không đúng.
        /// </summary>
        public static string DATA_REQUEST_IN_VALID {
            get {
                return ResourceManager.GetString("DATA_REQUEST_IN_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban đã có nhân viên. Không thể xóa.
        /// </summary>
        public static string DEPARTMENT_HAS_EMPLOYEE {
            get {
                return ResourceManager.GetString("DEPARTMENT_HAS_EMPLOYEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty không tồn tại phòng ban này.
        /// </summary>
        public static string DEPARTMENT_NOT_EXIST {
            get {
                return ResourceManager.GetString("DEPARTMENT_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sai định dạng.
        /// </summary>
        public static string EMAIL_NOT_FORMAT {
            get {
                return ResourceManager.GetString("EMAIL_NOT_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không được để trống.
        /// </summary>
        public static string EMAIL_REQUIRED {
            get {
                return ResourceManager.GetString("EMAIL_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ email đã được sử dụng ở công ty khác.
        /// </summary>
        public static string EMAIL_USED {
            get {
                return ResourceManager.GetString("EMAIL_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên đã có hợp đồng. Không thể xóa.
        /// </summary>
        public static string EMPLOYEE_HAS_CONTRACT {
            get {
                return ResourceManager.GetString("EMPLOYEE_HAS_CONTRACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có nhân viên không tồn tại trong công ty..
        /// </summary>
        public static string EMPLOYEE_NOT_EXIST_IN_COMPANY {
            get {
                return ResourceManager.GetString("EMPLOYEE_NOT_EXIST_IN_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi trong quá trình xử lý dữ liệu.
        /// </summary>
        public static string ERROR_ON_HANDLE_DATA {
            get {
                return ResourceManager.GetString("ERROR_ON_HANDLE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiên làm việc của bạn đã hết hạn. Vui lòng đăng nhập lại.
        /// </summary>
        public static string EXPIRES_TOKEN {
            get {
                return ResourceManager.GetString("EXPIRES_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra vui lòng thử lại sau.
        /// </summary>
        public static string HAS_ERROR {
            get {
                return ResourceManager.GetString("HAS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hết hạn phiên làm việc. Vui lòng thử lại sau..
        /// </summary>
        public static string INVALID_TOKEN_RESET {
            get {
                return ResourceManager.GetString("INVALID_TOKEN_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của bạn bị khóa tạm thời. Vui lòng thử lại sau..
        /// </summary>
        public static string LOCK_ACCOUNT {
            get {
                return ResourceManager.GetString("LOCK_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất thành công.
        /// </summary>
        public static string LOG_OUT_SUCCESS {
            get {
                return ResourceManager.GetString("LOG_OUT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu không chính xác.
        /// </summary>
        public static string LOGIN_FAILED {
            get {
                return ResourceManager.GetString("LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng nhân viên tối đa của hợp đồng mới phải lớn hơn hợp đồng cũ.
        /// </summary>
        public static string MAX_EMPLOYEE_ERROR {
            get {
                return ResourceManager.GetString("MAX_EMPLOYEE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tồn tại hợp đồng hoặc nhân viên muốn cập nhật.
        /// </summary>
        public static string NOT_EXIST_EM_CONTRACT {
            get {
                return ResourceManager.GetString("NOT_EXIST_EM_CONTRACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email người dùng không tồn tại.
        /// </summary>
        public static string NOT_EXIST_EMAIL {
            get {
                return ResourceManager.GetString("NOT_EXIST_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty chưa kích hoạt không thể thanh toán.
        /// </summary>
        public static string NOT_PAY_NEW {
            get {
                return ResourceManager.GetString("NOT_PAY_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa hết tháng thanh toán, vui lòng thử lại sau.
        /// </summary>
        public static string NOT_TO_PAY {
            get {
                return ResourceManager.GetString("NOT_TO_PAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ không đúng.
        /// </summary>
        public static string OLD_PASSWORD_INCORECT {
            get {
                return ResourceManager.GetString("OLD_PASSWORD_INCORECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá hợp đồng không tồn tại.
        /// </summary>
        public static string PRICE_CONTRACT_NOT_EXIST {
            get {
                return ResourceManager.GetString("PRICE_CONTRACT_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự án đã có nhân viên. Không được xóa..
        /// </summary>
        public static string PROJECT_EXIST_EMPLOYEE {
            get {
                return ResourceManager.GetString("PROJECT_EXIST_EMPLOYEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự án không tồn tại.
        /// </summary>
        public static string PROJECT_NOT_EXIST {
            get {
                return ResourceManager.GetString("PROJECT_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điều khoản đã tồn tại.
        /// </summary>
        public static string RULE_EXIST {
            get {
                return ResourceManager.GetString("RULE_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi email thành công. .
        /// </summary>
        public static string SEND_MAIL_SUCCESS {
            get {
                return ResourceManager.GetString("SEND_MAIL_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái không hợp lệ.
        /// </summary>
        public static string STATUS_ERROR {
            get {
                return ResourceManager.GetString("STATUS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công.
        /// </summary>
        public static string SUCCEED {
            get {
                return ResourceManager.GetString("SUCCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền truy cập chức năng này..
        /// </summary>
        public static string UN_AUTHOZIRED {
            get {
                return ResourceManager.GetString("UN_AUTHOZIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có ảnh được tải lên.
        /// </summary>
        public static string UPLOAD_FAILED {
            get {
                return ResourceManager.GetString("UPLOAD_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không tồn tại.
        /// </summary>
        public static string USER_NOT_EXIST {
            get {
                return ResourceManager.GetString("USER_NOT_EXIST", resourceCulture);
            }
        }
    }
}
